import type {
  Candidate,
  Targeting,
  Lens,
  Job,
  Company,
  Approval,
  Insights,
  SkillsGap,
} from "@specula/shared-types";

export const candidate: Candidate = {
  name: "Joris Veldkamp",
  initials: "JV",
  title: "Data Scientist / ML Engineer",
  location: "Amsterdam, NL",
  workMode: ["Remote", "Hybrid", "On-site"],
  visa: "EU/EEA/Swiss citizen — no sponsorship",
  years: 6,
  education: [
    {
      degree: "MSc",
      field: "Artificial Intelligence",
      institution: "University of Amsterdam",
      year: 2019,
    },
  ],
  languages: [
    { language: "English", level: "Native" },
    { language: "Dutch", level: "Native" },
    { language: "German", level: "B1" },
  ],
  skills: [
    "Python",
    "PyTorch",
    "LLM fine-tuning",
    "RAG",
    "LangGraph",
    "vLLM",
    "Pandas",
    "scikit-learn",
    "AWS",
    "Docker",
    "SQL",
    "FastAPI",
    "Weights & Biases",
    "Prompt engineering",
  ],
  projects: [
    {
      name: "Agentic research assistant",
      note: "LangGraph + vLLM multi-tool agent, self-hosted Llama-3 70B",
    },
    {
      name: "Churn forecasting pipeline",
      note: "Gradient-boosted ensemble, 0.91 AUC, productionised on AWS",
    },
    {
      name: "Semantic doc search",
      note: "pgvector RAG over 2M internal docs, sub-200ms p95",
    },
  ],
  experience: [
    {
      role: "Senior Data Scientist",
      org: "Mollie",
      startYear: 2022,
      endYear: null,
    },
    { role: "ML Engineer", org: "Adyen", startYear: 2019, endYear: 2022 },
  ],
};

export const targeting: Targeting = {
  roleTitles: [
    "Data Scientist",
    "ML Engineer",
    "Machine Learning Engineer",
    "AI Engineer",
    "AI Developer",
    "Applied Scientist",
    "Research Engineer",
  ],
  seniority: ["Mid", "Senior", "Staff"],
  mustHaves: [
    "Python",
    "Production ML or applied LLM work",
    "Remote-friendly within EU",
  ],
  avoid: [
    "Pure research / publish-or-perish",
    "Defense primary mission",
    "Relocation required",
    "On-call heavy SRE",
  ],
  preferences:
    "Strongly prefer agentic-systems / applied-LLM engineering over pure research. Remote-EU friendly, async culture. Happy with hybrid in NL/DE. Interested in inference, retrieval, and agent infrastructure.",
};

export const lenses: Lens[] = [
  {
    id: "all",
    name: "All",
    short: "All",
    active: true,
    scope: "Any region",
    modes: ["Remote", "Hybrid", "On-site"],
    origin: "",
    focus: "",
    seeds: ["data scientist", "ML engineer", "applied scientist"],
  },
  {
    id: "remote",
    name: "Remote · EU",
    short: "Remote · EU",
    active: true,
    scope: "EU",
    modes: ["Remote"],
    origin: "",
    focus: "fully-remote, async-first teams",
    seeds: ["remote ML engineer EU", "fully remote applied scientist europe"],
  },
  {
    id: "foreign",
    name: "Foreign HQ",
    short: "Foreign HQ",
    active: true,
    scope: "EU",
    modes: ["Remote", "Hybrid"],
    origin: "foreign_hq",
    focus: "non-NL HQ — broaden beyond home market",
    seeds: ["US startup hiring remote EU", "foreign AI lab europe team"],
  },
  {
    id: "spain",
    name: "Spain",
    short: "Spain",
    active: true,
    scope: "ES",
    modes: ["Remote", "Hybrid", "On-site"],
    origin: "",
    focus: "Barcelona / Madrid relocation-optional",
    seeds: ["machine learning engineer Barcelona", "data scientist Madrid"],
  },
  {
    id: "berlin",
    name: "Berlin core",
    short: "Berlin",
    active: false,
    scope: "Berlin, DE",
    modes: ["Hybrid", "On-site"],
    origin: "",
    focus: "Berlin AI scene, hybrid acceptable",
    seeds: ["AI engineer Berlin", "LLM engineer Berlin hybrid"],
  },
];

export const jobs: Job[] = [
  {
    id: "j1",
    company: "Mistral AI",
    logo: "MA",
    title: "Applied Scientist — LLM Agents",
    city: "Paris",
    country: "FR",
    hq: "FR",
    mode: "Hybrid",
    flag: "🇫🇷",
    match: 94,
    factors: { role: 96, skill: 89, loc: 92 },
    overlap: [8, 9],
    seniority: "Senior",
    edu: "MSc preferred",
    deadlineDays: 9,
    salary: "€95k–130k",
    posted: "4d ago",
    status: null,
    isNew: true,
    stillOpen: true,
    originVerified: true,
    hqConf: 98,
    stack: ["PyTorch", "vLLM", "Python", "Kubernetes", "Ray", "LangGraph"],
    niceToHave: ["JAX", "Triton kernels"],
    visa: "EU work auth required",
    langs: ["English C1"],
    contract: "Permanent",
    geo: "EU timezone",
    confidence: 96,
    responsibilities: [
      "Design and evaluate tool-using LLM agents",
      "Build agent eval harnesses and traces",
      "Ship retrieval + planning into production",
      "Collaborate with research on new architectures",
    ],
    summary:
      "Build production-grade tool-using LLM agents — planning, retrieval and evaluation — alongside Mistral's research team in Paris, hybrid 2 days on-site.",
    rationale:
      "Agentic-LLM focus maps directly onto your applied-LLM preference; remote-EU friendly with strong skill overlap (8 of 9 required).",
  },
  {
    id: "j2",
    company: "Helsing",
    logo: "HS",
    title: "Senior Machine Learning Engineer",
    city: "Munich",
    country: "DE",
    hq: "DE",
    mode: "Hybrid",
    flag: "🇩🇪",
    match: 88,
    factors: { role: 90, skill: 86, loc: 78 },
    overlap: [7, 9],
    seniority: "Senior",
    edu: "MSc / PhD",
    deadlineDays: 14,
    salary: null,
    posted: "6d ago",
    status: "Saved",
    isNew: false,
    stillOpen: true,
    originVerified: true,
    hqConf: 95,
    stack: ["PyTorch", "C++", "CUDA", "ONNX", "Triton"],
    niceToHave: ["TensorRT", "Real-time systems"],
    visa: "EU work auth required",
    langs: ["English C1", "German nice"],
    contract: "Permanent",
    geo: "Munich hybrid",
    confidence: 92,
    responsibilities: [
      "Optimise model inference on edge hardware",
      "Own training-to-deployment pipelines",
      "Profile and accelerate PyTorch graphs",
    ],
    summary:
      "Systems-leaning ML role optimising real-time inference. Strong engineering depth; defense-adjacent mission and Munich hybrid expectation.",
    rationale:
      "High overlap and strong systems-ML fit; Munich on-site bias and the defense-adjacent domain are mild fit risks against your stated preferences.",
  },
  {
    id: "j3",
    company: "DeepL",
    logo: "DL",
    title: "ML Engineer — Inference",
    city: "Remote · EU",
    country: "NL",
    hq: "DE",
    mode: "Remote",
    flag: "🇳🇱",
    match: 84,
    factors: { role: 84, skill: 88, loc: 96 },
    overlap: [7, 8],
    seniority: "Mid–Senior",
    edu: "BSc",
    deadlineDays: 21,
    salary: "€80k–110k",
    posted: "2d ago",
    status: null,
    isNew: true,
    stillOpen: true,
    originVerified: true,
    hqConf: 97,
    stack: ["PyTorch", "Triton", "AWS", "Python", "Docker"],
    niceToHave: ["Rust", "Quantisation"],
    visa: "EU remote OK",
    langs: ["English C1"],
    contract: "Permanent",
    geo: "EU remote",
    confidence: 94,
    responsibilities: [
      "Serve translation models at low latency",
      "Build autoscaling inference infra",
      "Quantise and distil production models",
    ],
    summary:
      "Fully remote-EU inference engineering at DeepL — latency, autoscaling and quantisation of large translation models.",
    rationale:
      "Fully remote-EU with clean skill overlap (7 of 8); lighter on agentic work than you ideally want, but strong on the infra you enjoy.",
  },
  {
    id: "j4",
    company: "ElevenLabs",
    logo: "EL",
    title: "Applied Research Engineer — Audio LLMs",
    city: "Remote · EU",
    country: "NL",
    hq: "GB",
    mode: "Remote",
    flag: "🇳🇱",
    match: 81,
    factors: { role: 80, skill: 79, loc: 90 },
    overlap: [6, 9],
    seniority: "Senior",
    edu: "MSc preferred",
    deadlineDays: 30,
    salary: null,
    posted: "8d ago",
    status: null,
    isNew: false,
    stillOpen: true,
    originVerified: true,
    hqConf: 91,
    stack: ["PyTorch", "Python", "JAX", "AWS"],
    niceToHave: ["Audio DSP", "Diffusion"],
    visa: "EU remote OK",
    langs: ["English C1"],
    contract: "Permanent",
    geo: "EU/UK remote",
    confidence: 88,
    responsibilities: [
      "Train and fine-tune audio-language models",
      "Design evaluation for generative audio",
      "Collaborate across research and product",
    ],
    summary:
      "Foreign-HQ (UK) remote role on audio-language models — training, fine-tuning and eval, adjacent to your core LLM work.",
    rationale:
      "Matches your Foreign-HQ lens; audio-LLM work is adjacent to your core and fully remote, with decent overlap (6 of 9).",
  },
  {
    id: "j5",
    company: "Sereact",
    logo: "SR",
    title: "Research Engineer — Robotics Foundation Models",
    city: "Remote · EU",
    country: "NL",
    hq: "DE",
    mode: "Remote",
    flag: "🇳🇱",
    match: 71,
    factors: { role: 74, skill: 41, loc: 92 },
    overlap: [2, 8],
    seniority: "Senior",
    edu: "PhD preferred",
    deadlineDays: 5,
    salary: null,
    posted: "11d ago",
    status: null,
    isNew: false,
    stillOpen: true,
    originVerified: false,
    hqConf: 64,
    redFlag: "Low required-skill overlap",
    stack: ["PyTorch", "ROS", "C++", "Isaac Sim"],
    niceToHave: ["RL", "Sim2real"],
    visa: "EU remote OK",
    langs: ["English C1"],
    contract: "Permanent",
    geo: "EU remote",
    confidence: 79,
    responsibilities: [
      "Train robot manipulation policies",
      "Build sim-to-real pipelines",
      "Scale multi-task robot learning",
    ],
    summary:
      "Robotics foundation-model research. Strong role and location fit, but the robotics/sim stack diverges sharply from your profile.",
    rationale:
      "Near-zero required-skill overlap (2 of 8) on a robotics/sim stack pulls this down as a one-way red flag despite good role and location fit. HQ origin unverified (64%).",
  },
  {
    id: "j6",
    company: "Pigment",
    logo: "PG",
    title: "Senior Data Scientist — Forecasting",
    city: "Paris",
    country: "FR",
    hq: "FR",
    mode: "Hybrid",
    flag: "🇫🇷",
    match: 68,
    factors: { role: 66, skill: 72, loc: 80 },
    overlap: [5, 9],
    seniority: "Senior",
    edu: "MSc",
    deadlineDays: 18,
    salary: "€70k–95k",
    posted: "9d ago",
    status: "Applied",
    isNew: false,
    stillOpen: true,
    originVerified: true,
    hqConf: 96,
    stack: ["Python", "dbt", "Snowflake", "Prophet", "SQL"],
    niceToHave: ["Causal inference"],
    visa: "EU work auth required",
    langs: ["English C1", "French nice"],
    contract: "Permanent",
    geo: "Paris hybrid",
    confidence: 90,
    responsibilities: [
      "Build demand-forecasting models",
      "Partner with product on planning analytics",
      "Own metric pipelines",
    ],
    summary:
      "BI/forecasting-leaning data science at a planning platform. Solid but further from applied-LLM than you target.",
    rationale:
      "Forecasting/BI lean sits further from your applied-LLM target, but overlap is reasonable (5 of 9) and it's a clean Paris hybrid you already applied to.",
  },
  {
    id: "j7",
    company: "Qonto",
    logo: "QO",
    title: "Machine Learning Engineer — Fraud",
    city: "Barcelona",
    country: "ES",
    hq: "FR",
    mode: "Hybrid",
    flag: "🇪🇸",
    match: 79,
    factors: { role: 78, skill: 82, loc: 74 },
    overlap: [6, 8],
    seniority: "Senior",
    edu: "MSc",
    deadlineDays: 12,
    salary: "€68k–88k",
    posted: "3d ago",
    status: null,
    isNew: true,
    stillOpen: true,
    originVerified: true,
    hqConf: 93,
    stack: ["Python", "PyTorch", "AWS", "SQL", "Kafka"],
    niceToHave: ["Graph ML", "Streaming"],
    visa: "EU work auth required",
    langs: ["English C1", "Spanish nice"],
    contract: "Permanent",
    geo: "Barcelona hybrid",
    confidence: 91,
    responsibilities: [
      "Build real-time fraud detection models",
      "Own streaming feature pipelines",
      "Reduce false positives at scale",
    ],
    summary:
      "Foreign-HQ (FR) fintech ML role in Barcelona — real-time fraud detection, streaming features. Matches both your Spain and Foreign-HQ lenses.",
    rationale:
      "Appears in your Spain and Foreign-HQ lenses; fintech ML aligns with your Adyen/Mollie background and overlap is solid (6 of 8).",
  },
  {
    id: "j8",
    company: "Synthesia",
    logo: "SY",
    title: "AI Engineer — Generative Video",
    city: "Remote · EU",
    country: "NL",
    hq: "GB",
    mode: "Remote",
    flag: "🇳🇱",
    match: 77,
    factors: { role: 76, skill: 75, loc: 90 },
    overlap: [6, 9],
    seniority: "Mid–Senior",
    edu: "BSc",
    deadlineDays: 25,
    salary: "€75k–100k",
    posted: "5d ago",
    status: null,
    isNew: true,
    stillOpen: true,
    originVerified: true,
    hqConf: 90,
    stack: ["Python", "PyTorch", "Diffusion", "AWS", "FastAPI"],
    niceToHave: ["CUDA", "Video pipelines"],
    visa: "EU remote OK",
    langs: ["English C1"],
    contract: "Permanent",
    geo: "EU remote",
    confidence: 87,
    responsibilities: [
      "Productionise generative video models",
      "Build inference APIs for avatars",
      "Optimise generation latency",
    ],
    summary:
      "Foreign-HQ (UK) remote AI engineering on generative video — productionising diffusion models behind real APIs.",
    rationale:
      "Foreign-HQ remote match; applied generative work with FastAPI/AWS overlaps your stack, though video is adjacent to your LLM focus.",
  },
  {
    id: "j9",
    company: "Aleph Alpha",
    logo: "AA",
    title: "ML Engineer — Retrieval & RAG",
    city: "Heidelberg",
    country: "DE",
    hq: "DE",
    mode: "Hybrid",
    flag: "🇩🇪",
    match: 85,
    factors: { role: 88, skill: 90, loc: 70 },
    overlap: [8, 9],
    seniority: "Senior",
    edu: "MSc",
    deadlineDays: 7,
    salary: "€85k–115k",
    posted: "1d ago",
    status: null,
    isNew: true,
    stillOpen: true,
    originVerified: true,
    hqConf: 95,
    stack: ["Python", "PyTorch", "pgvector", "RAG", "LangGraph", "Docker"],
    niceToHave: ["Sparse retrieval", "Eval frameworks"],
    visa: "EU work auth required",
    langs: ["English C1", "German nice"],
    contract: "Permanent",
    geo: "Heidelberg hybrid",
    confidence: 93,
    responsibilities: [
      "Build sovereign-LLM retrieval systems",
      "Own RAG eval and grounding",
      "Ship enterprise retrieval at scale",
    ],
    summary:
      "Retrieval & RAG engineering for a European sovereign-LLM lab — exactly your pgvector/RAG/LangGraph wheelhouse. Heidelberg hybrid.",
    rationale:
      "Highest skill overlap in your pool (8 of 9) — pgvector, RAG and LangGraph are core to your projects. Heidelberg hybrid is the only friction.",
  },
  {
    id: "j10",
    company: "Wayve",
    logo: "WV",
    title: "Applied Scientist — Foundation Models",
    city: "Remote",
    country: "GB",
    hq: "GB",
    mode: "Remote",
    flag: "🇬🇧",
    match: 73,
    factors: { role: 75, skill: 68, loc: 88 },
    overlap: [5, 9],
    seniority: "Senior",
    edu: "PhD preferred",
    deadlineDays: 16,
    salary: null,
    posted: "10d ago",
    status: "Dismissed",
    isNew: false,
    stillOpen: true,
    originVerified: true,
    hqConf: 89,
    stack: ["PyTorch", "Python", "JAX", "Distributed training"],
    niceToHave: ["Autonomy", "Multimodal"],
    visa: "EU remote OK",
    langs: ["English C1"],
    contract: "Permanent",
    geo: "EU/UK remote",
    confidence: 85,
    dismissReason: "Not my field",
    responsibilities: [
      "Train large driving foundation models",
      "Scale distributed training",
      "Research multimodal architectures",
    ],
    summary:
      "Foreign-HQ remote applied science on driving foundation models — heavy research and autonomy-domain, lighter on your applied-LLM core.",
    rationale:
      "Research-heavy and autonomy-domain — you dismissed it as 'not my field'. Logged as a negative signal to steer future scoring.",
  },
  {
    id: "j11",
    company: "Parloa",
    logo: "PA",
    title: "ML Engineer — Voice Agents",
    city: "Berlin",
    country: "DE",
    hq: "DE",
    mode: "Hybrid",
    flag: "🇩🇪",
    match: 86,
    factors: { role: 89, skill: 87, loc: 76 },
    overlap: [7, 9],
    seniority: "Senior",
    edu: "MSc",
    deadlineDays: 11,
    salary: "€82k–108k",
    posted: "3d ago",
    status: null,
    isNew: true,
    stillOpen: true,
    originVerified: true,
    hqConf: 94,
    stack: ["Python", "PyTorch", "LangGraph", "vLLM", "AWS", "FastAPI"],
    niceToHave: ["Telephony", "Streaming ASR"],
    visa: "EU work auth required",
    langs: ["English C1", "German nice"],
    contract: "Permanent",
    geo: "Berlin hybrid",
    confidence: 92,
    responsibilities: [
      "Build production voice-agent pipelines",
      "Own LLM orchestration with LangGraph",
      "Optimise latency for real-time calls",
    ],
    summary:
      "Agentic voice-AI engineering in Berlin — LangGraph orchestration, real-time LLM agents. Squarely in your agentic-systems wheelhouse.",
    rationale:
      "Strong agentic-systems match — LangGraph and vLLM are core to your projects (7 of 9). Berlin hybrid is the only friction against your remote preference.",
  },
  {
    id: "j12",
    company: "Ada Health",
    logo: "AD",
    title: "AI Engineer — Clinical LLMs",
    city: "Berlin",
    country: "DE",
    hq: "DE",
    mode: "Hybrid",
    flag: "🇩🇪",
    match: 78,
    factors: { role: 80, skill: 78, loc: 76 },
    overlap: [6, 9],
    seniority: "Mid–Senior",
    edu: "MSc",
    deadlineDays: 19,
    salary: "€75k–98k",
    posted: "7d ago",
    status: null,
    isNew: false,
    stillOpen: true,
    originVerified: true,
    hqConf: 93,
    stack: ["Python", "PyTorch", "RAG", "pgvector", "AWS"],
    niceToHave: ["Healthcare data", "Eval"],
    visa: "EU work auth required",
    langs: ["English C1"],
    contract: "Permanent",
    geo: "Berlin hybrid",
    confidence: 89,
    responsibilities: [
      "Build retrieval over clinical knowledge",
      "Ground LLM outputs with citations",
      "Ship safe medical assistants",
    ],
    summary:
      "Clinical-LLM and RAG engineering in Berlin — grounded retrieval over medical knowledge, your pgvector/RAG core in a regulated domain.",
    rationale:
      "RAG + pgvector overlap your projects well (6 of 9); regulated healthcare domain is new ground but adjacent. Berlin hybrid in your Berlin lens.",
  },
  {
    id: "j13",
    company: "Factorial",
    logo: "FC",
    title: "Machine Learning Engineer — Recommendations",
    city: "Barcelona",
    country: "ES",
    hq: "ES",
    mode: "Hybrid",
    flag: "🇪🇸",
    match: 74,
    factors: { role: 74, skill: 78, loc: 72 },
    overlap: [6, 8],
    seniority: "Senior",
    edu: "MSc",
    deadlineDays: 23,
    salary: "€60k–82k",
    posted: "6d ago",
    status: null,
    isNew: true,
    stillOpen: true,
    originVerified: true,
    hqConf: 92,
    stack: ["Python", "PyTorch", "SQL", "AWS", "Airflow"],
    niceToHave: ["Recsys", "Feature stores"],
    visa: "EU work auth required",
    langs: ["English C1", "Spanish nice"],
    contract: "Permanent",
    geo: "Barcelona hybrid",
    confidence: 88,
    responsibilities: [
      "Build recommendation models for HR software",
      "Own feature pipelines",
      "Run online experiments",
    ],
    summary:
      "Recommendation-systems ML at a Barcelona HR-software scaleup — solid applied ML, lighter on LLM/agents than you target.",
    rationale:
      "Appears in your Spain lens; applied ML with a familiar stack (6 of 8), though recsys sits further from your applied-LLM focus.",
  },
];

export const companies: Company[] = [
  {
    name: "Mistral AI",
    logo: "MA",
    domain: "mistral.ai",
    ats: "Greenhouse",
    hq: "France",
    flag: "🇫🇷",
    conf: 98,
    open: 12,
    comp: "€€€",
    added: "Mar 2026",
  },
  {
    name: "Aleph Alpha",
    logo: "AA",
    domain: "aleph-alpha.com",
    ats: "Greenhouse",
    hq: "Germany",
    flag: "🇩🇪",
    conf: 95,
    open: 8,
    comp: "€€€",
    added: "Mar 2026",
  },
  {
    name: "Helsing",
    logo: "HS",
    domain: "helsing.ai",
    ats: "Lever",
    hq: "Germany",
    flag: "🇩🇪",
    conf: 95,
    open: 7,
    comp: "€€€",
    added: "Feb 2026",
  },
  {
    name: "DeepL",
    logo: "DL",
    domain: "deepl.com",
    ats: "Greenhouse",
    hq: "Germany",
    flag: "🇩🇪",
    conf: 97,
    open: 9,
    comp: "€€",
    added: "Feb 2026",
  },
  {
    name: "ElevenLabs",
    logo: "EL",
    domain: "elevenlabs.io",
    ats: "Ashby",
    hq: "United Kingdom",
    flag: "🇬🇧",
    conf: 91,
    open: 6,
    comp: "€€€",
    added: "Apr 2026",
  },
  {
    name: "Qonto",
    logo: "QO",
    domain: "qonto.com",
    ats: "Lever",
    hq: "France",
    flag: "🇫🇷",
    conf: 93,
    open: 5,
    comp: "€€",
    added: "Apr 2026",
  },
  {
    name: "Synthesia",
    logo: "SY",
    domain: "synthesia.io",
    ats: "Ashby",
    hq: "United Kingdom",
    flag: "🇬🇧",
    conf: 90,
    open: 4,
    comp: "€€",
    added: "Apr 2026",
  },
  {
    name: "Pigment",
    logo: "PG",
    domain: "pigment.com",
    ats: "Greenhouse",
    hq: "France",
    flag: "🇫🇷",
    conf: 96,
    open: 6,
    comp: "€€",
    added: "Jan 2026",
  },
  {
    name: "Sereact",
    logo: "SR",
    domain: "sereact.ai",
    ats: "Ashby",
    hq: "Germany",
    flag: "🇩🇪",
    conf: 64,
    open: 3,
    comp: "€€",
    added: "May 2026",
    unverified: true,
  },
  {
    name: "Wayve",
    logo: "WV",
    domain: "wayve.ai",
    ats: "Greenhouse",
    hq: "United Kingdom",
    flag: "🇬🇧",
    conf: 89,
    open: 7,
    comp: "€€€",
    added: "Jan 2026",
  },
];

export const approvals: Approval[] = [
  {
    id: "a1",
    name: "Black Forest Labs",
    logo: "BF",
    domain: "blackforestlabs.ai",
    careersUrl: "https://jobs.ashbyhq.com/blackforestlabs",
    ats: "Ashby",
    hq: "Germany",
    flag: "🇩🇪",
    query: "diffusion model lab europe hiring",
    why: "Generative-image research lab (FLUX). Matches your applied-LLM/generative targeting; small team, Freiburg + remote.",
    roles: 4,
  },
  {
    id: "a2",
    name: "Lighthouse",
    logo: "LH",
    domain: "lighthouse.app",
    careersUrl: "https://boards.greenhouse.io/lighthouse",
    ats: "Greenhouse",
    hq: "Netherlands",
    flag: "🇳🇱",
    query: "machine learning amsterdam scaleup",
    why: "Amsterdam travel-tech scaleup with a growing ML team. NL-local, matches your home market and remote-EU lens.",
    roles: 3,
  },
  {
    id: "a3",
    name: "n8n",
    logo: "N8",
    domain: "n8n.io",
    careersUrl: "https://jobs.lever.co/n8n",
    ats: "Lever",
    hq: "Germany",
    flag: "🇩🇪",
    query: "AI workflow automation hiring engineer",
    why: "Workflow-automation platform investing in AI agents. Strong agentic angle aligned with your stated preference.",
    roles: 5,
  },
  {
    id: "a4",
    name: "Tractable",
    logo: "TR",
    domain: "tractable.ai",
    careersUrl: "https://boards.greenhouse.io/tractable",
    ats: "Greenhouse",
    hq: "United Kingdom",
    flag: "🇬🇧",
    query: "applied computer vision europe remote",
    why: "Applied CV for insurance. Foreign-HQ remote-EU; CV-heavy, somewhat adjacent to your LLM focus.",
    roles: 2,
  },
  {
    id: "a5",
    name: "Sereact",
    logo: "SR",
    domain: "sereact.ai",
    ats: "Ashby",
    hq: "Germany",
    flag: "🇩🇪",
    query: "robotics foundation models hiring",
    why: "Robotics foundation-model startup. HQ origin only 64% confident — flagged 'origin unverified'.",
    careersUrl: "https://jobs.ashbyhq.com/sereact",
    roles: 3,
    unverified: true,
  },
  {
    id: "a6",
    name: "Poolside",
    logo: "PS",
    domain: "poolside.ai",
    careersUrl: "https://jobs.ashbyhq.com/poolside",
    ats: "Ashby",
    hq: "United States",
    flag: "🇺🇸",
    query: "code LLM lab hiring remote europe",
    why: "Code-generation LLM lab hiring across EU remotely. Foreign-HQ (US); applied-LLM core, strong on paper.",
    roles: 6,
  },
];

export const insights: Insights = {
  period: "Last 8 weeks",
  totalAnalysed: 312,
  lowConfExcluded: 24,
  skillDemand: [
    { skill: "LLM / RAG", pct: 88, delta: +14, up: true },
    { skill: "PyTorch", pct: 81, delta: +3, up: true },
    { skill: "Kubernetes", pct: 64, delta: +9, up: true, gap: true },
    { skill: "vLLM / Triton", pct: 47, delta: +21, up: true },
    { skill: "AWS / GCP", pct: 72, delta: -2, up: false },
    { skill: "Go", pct: 29, delta: +6, up: true, gap: true },
    { skill: "Spark", pct: 22, delta: -8, up: false },
  ],
  trend: {
    weeks: ["w1", "w2", "w3", "w4", "w5", "w6", "w7", "w8"],
    series: [
      {
        name: "LLM / RAG",
        color: "var(--accent)",
        data: [34, 38, 41, 45, 52, 58, 64, 71],
      },
      {
        name: "Inference / vLLM",
        color: "#9A7A18",
        data: [12, 14, 13, 18, 22, 27, 31, 38],
      },
      {
        name: "Classical ML",
        color: "var(--ink-2)",
        data: [40, 38, 37, 35, 33, 31, 30, 28],
      },
    ],
  },
  seniorityMix: [
    { k: "Junior", v: 8 },
    { k: "Mid", v: 24 },
    { k: "Senior", v: 46 },
    { k: "Staff", v: 16 },
    { k: "Lead", v: 6 },
  ],
  modeMix: [
    { k: "Remote", v: 41, color: "var(--accent)" },
    { k: "Hybrid", v: 38, color: "var(--ink)" },
    { k: "On-site", v: 21, color: "var(--ink-3)" },
  ],
  salary: [
    { band: "€60–80k", lo: 6, hi: 40 },
    { band: "€80–100k", lo: 30, hi: 68 },
    { band: "€100–130k", lo: 55, hi: 88 },
    { band: "€130k+", lo: 78, hi: 100 },
  ],
  activeCompanies: [
    { name: "Mistral AI", n: 12 },
    { name: "DeepL", n: 9 },
    { name: "Aleph Alpha", n: 8 },
    { name: "Wayve", n: 7 },
    { name: "Helsing", n: 7 },
  ],
};

export const skillsGap: SkillsGap[] = [
  {
    skill: "Kubernetes",
    roles: 6,
    note: "appears in 6 of your target roles, not on your profile",
  },
  {
    skill: "Triton / TensorRT",
    roles: 4,
    note: "inference roles increasingly require kernel-level work",
  },
  {
    skill: "Go",
    roles: 3,
    note: "platform/infra roles list Go alongside Python",
  },
  {
    skill: "Distributed training",
    roles: 3,
    note: "staff-level roles expect multi-node training",
  },
];
