// Frontend-only suggestion list for the Skills typeahead (a <datalist>). NOT a
// server constraint — any typed value is still accepted (free-add). Nudges toward
// canonical spellings so matching (which canonicalizes skills) stays clean.
export const COMMON_SKILLS: string[] = [
  "Python",
  "PyTorch",
  "TensorFlow",
  "JAX",
  "Hugging Face",
  "LLM fine-tuning",
  "RAG",
  "LangGraph",
  "LangChain",
  "vLLM",
  "Triton / TensorRT",
  "ONNX",
  "Distributed training",
  "Ray",
  "Spark",
  "Airflow",
  "dbt",
  "Snowflake",
  "Kafka",
  "Pandas",
  "NumPy",
  "scikit-learn",
  "XGBoost",
  "MLflow",
  "Weights & Biases",
  "Kubeflow",
  "Prompt engineering",
  "pgvector",
  "AWS",
  "GCP",
  "Azure",
  "Docker",
  "Kubernetes",
  "Terraform",
  "SQL",
  "FastAPI",
  "Go",
  "Rust",
  "TypeScript",
  "React",
  "Redis",
  "PostgreSQL",
];
